version: '2'
services:
  mysql:
    container_name: go_mysql
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'swapnil' # TODO: Change this
      MYSQL_USER: 'swapnil'
      MYSQL_PASS: 'swapnil'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
